Updated readme, command on event future

diff --git a/contrib/log_event_monitor b/contrib/log_event_monitor
--- a/contrib/log_event_monitor
+++ b/contrib/log_event_monitor
@@ -5,50 +5,68 @@
 # processname: log_event_monitor
 
 
-DAEMON="/home/k.shatsky/log_event_monitor/log_event_monitor.py"
+DAEMON="/opt/scripts/log_event_monitor/log_event_monitor.py"
 DAEMONOPTS=""
 
 NAME=log_event_monitor
-DESC="My daemon description"
+DESC="Log Event Monitor Daemon"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
-case "$1" in
-start)
-	printf "%-50s" "Starting $NAME..."
+function start_process {
+        PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
 
-	PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
-
-	echo "Saving PID" $PID " to " $PIDFILE
+        echo "Saving PID" $PID " to " $PIDFILE
         if [ -z $PID ]; then
             printf "%s\n" "Fail"
         else
             echo $PID > $PIDFILE
             printf "%s\n" "Ok"
         fi
+}
+
+case "$1" in
+start)
+	printf "%-50s" "Starting $NAME...\n"
+
+	if [ -f $PIDFILE ]; then
+
+            PID=`cat $PIDFILE`
+
+            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+	        printf "Demon %s already running" $DAEMON
+	        exit 1;
+            else
+                start_process
+            fi
+
+	else
+            start_process
+        fi
 ;;
 status)
-        printf "%-50s" "Checking $NAME..."
+        printf "%-50s" "Checking $NAME...\n"
         if [ -f $PIDFILE ]; then
             PID=`cat $PIDFILE`
             if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-                printf "%s\n" "Process dead but pidfile exists"
+                printf "%s" "Process dead but pidfile exists"
             else
                 echo "Running"
             fi
         else
-            printf "%s\n" "Service not running"
+            printf "%s" "Service not running"
         fi
 ;;
 stop)
         printf "%-50s" "Stopping $NAME"
             PID=`cat $PIDFILE`
         if [ -f $PIDFILE ]; then
-            kill -HUP $PID
+            #kill -HUP $PID
+            pkill -P $PID
             printf "%s\n" "Ok"
             rm -f $PIDFILE
         else
-            printf "%s\n" "pidfile not found"
+            printf "%s" "pidfile not found"
         fi
 ;;
 
